DROP TABLE IF EXISTS system_analyst;
DROP TABLE IF EXISTS research_scientist;
DROP TABLE IF EXISTS database_admins;
DROP TABLE IF EXISTS operations_analyst;
DROP TABLE IF EXISTS statistician;
DROP TABLE IF EXISTS computer_programmer;
DROP TABLE IF EXISTS web_developer;
DROP TABLE IF EXISTS data_scientist;

CREATE TABLE system_analyst (
	"AREA" int,
	"AREA_TITLE" varchar(80),
	--"AREA_TYPE" int,
	--"PRIM_STATE" varchar(3),
	--"NAICS" int,
	--"NAICS_TITLE" varchar(80),
	--"I_GROUP" varchar(80),
	--"OWN_CODE" int,
	"OCC_TITLE" varchar(80),
	"OCC_CODE" varchar,
	--"O_GROUP" varchar(30),
	"TOT_EMP" varchar,
	--"EMP_PRSE" varchar,
	"JOBS_1000" varchar,
	"LOC_QUOTIENT" varchar,
--	"PCT_TOTAL" varchar,
	--"MEAN_PRSE" varchar,
	"H_PCT10" varchar,
	"H_PCT25" varchar,
	"H_MEDIAN" varchar,
	"H_MEAN" varchar,
	"H_PCT75" varchar,
	"H_PCT90" varchar,
	"A_PCT10" varchar,
	"A_PCT25" varchar,
	"A_MEDIAN" varchar,
	"A_MEAN" varchar,
	"A_PCT75" varchar,
	"A_PCT90" varchar,
	--"ANNUAL" int,
	--"HOURLY" int,
	PRIMARY KEY ("AREA_TITLE")
);

CREATE TABLE research_scientist (
	"AREA" int,
	"AREA_TITLE" varchar(80),
	--"AREA_TYPE" int,
	--"PRIM_STATE" varchar(3),
	--"NAICS" int,
	--"NAICS_TITLE" varchar(80),
	--"I_GROUP" varchar(80),
	--"OWN_CODE" int,
	"OCC_TITLE" varchar(80),
	"OCC_CODE" varchar,
	--"O_GROUP" varchar(30),
	"TOT_EMP" varchar,
	--"EMP_PRSE" varchar,
	"JOBS_1000" varchar,
	"LOC_QUOTIENT" varchar,
--	"PCT_TOTAL" varchar,
	--"MEAN_PRSE" varchar,
	"H_PCT10" varchar,
	"H_PCT25" varchar,
	"H_MEDIAN" varchar,
	"H_MEAN" varchar,
	"H_PCT75" varchar,
	"H_PCT90" varchar,
	"A_PCT10" varchar,
	"A_PCT25" varchar,
	"A_MEDIAN" varchar,
	"A_MEAN" varchar,
	"A_PCT75" varchar,
	"A_PCT90" varchar,
	--"ANNUAL" int,
	--"HOURLY" int,
	PRIMARY KEY ("AREA_TITLE")
);
	
CREATE TABLE database_admins (
	"AREA" int,
	"AREA_TITLE" varchar(80),
	--"AREA_TYPE" int,
	--"PRIM_STATE" varchar(3),
	--"NAICS" int,
	--"NAICS_TITLE" varchar(80),
	--"I_GROUP" varchar(80),
	--"OWN_CODE" int,
	"OCC_TITLE" varchar(80),
	"OCC_CODE" varchar,
	--"O_GROUP" varchar(30),
	"TOT_EMP" varchar,
	--"EMP_PRSE" varchar,
	"JOBS_1000" varchar,
	"LOC_QUOTIENT" varchar,
--	"PCT_TOTAL" varchar,
	--"MEAN_PRSE" varchar,
	"H_PCT10" varchar,
	"H_PCT25" varchar,
	"H_MEDIAN" varchar,
	"H_MEAN" varchar,
	"H_PCT75" varchar,
	"H_PCT90" varchar,
	"A_PCT10" varchar,
	"A_PCT25" varchar,
	"A_MEDIAN" varchar,
	"A_MEAN" varchar,
	"A_PCT75" varchar,
	"A_PCT90" varchar,
	--"ANNUAL" int,
	--"HOURLY" int,
	PRIMARY KEY ("AREA_TITLE")
);

CREATE TABLE operations_analyst (
	"AREA" int,
	"AREA_TITLE" varchar(80),
	--"AREA_TYPE" int,
	--"PRIM_STATE" varchar(3),
	--"NAICS" int,
	--"NAICS_TITLE" varchar(80),
	--"I_GROUP" varchar(80),
	--"OWN_CODE" int,
	"OCC_TITLE" varchar(80),
	"OCC_CODE" varchar,
	--"O_GROUP" varchar(30),
	"TOT_EMP" varchar,
	--"EMP_PRSE" varchar,
	"JOBS_1000" varchar,
	"LOC_QUOTIENT" varchar,
--	"PCT_TOTAL" varchar,
	--"MEAN_PRSE" varchar,
	"H_PCT10" varchar,
	"H_PCT25" varchar,
	"H_MEDIAN" varchar,
	"H_MEAN" varchar,
	"H_PCT75" varchar,
	"H_PCT90" varchar,
	"A_PCT10" varchar,
	"A_PCT25" varchar,
	"A_MEDIAN" varchar,
	"A_MEAN" varchar,
	"A_PCT75" varchar,
	"A_PCT90" varchar,
	--"ANNUAL" int,
	--"HOURLY" int,
	PRIMARY KEY ("AREA_TITLE")
);

CREATE TABLE statistician (
	"AREA" int,
	"AREA_TITLE" varchar(80),
	--"AREA_TYPE" int,
	--"PRIM_STATE" varchar(3),
	--"NAICS" int,
	--"NAICS_TITLE" varchar(80),
	--"I_GROUP" varchar(80),
	--"OWN_CODE" int,
	"OCC_TITLE" varchar(80),
	"OCC_CODE" varchar,
	--"O_GROUP" varchar(30),
	"TOT_EMP" varchar,
	--"EMP_PRSE" varchar,
	"JOBS_1000" varchar,
	"LOC_QUOTIENT" varchar,
--	"PCT_TOTAL" varchar,
	--"MEAN_PRSE" varchar,
	"H_PCT10" varchar,
	"H_PCT25" varchar,
	"H_MEDIAN" varchar,
	"H_MEAN" varchar,
	"H_PCT75" varchar,
	"H_PCT90" varchar,
	"A_PCT10" varchar,
	"A_PCT25" varchar,
	"A_MEDIAN" varchar,
	"A_MEAN" varchar,
	"A_PCT75" varchar,
	"A_PCT90" varchar,
	--"ANNUAL" int,
	--"HOURLY" int,
	PRIMARY KEY ("AREA_TITLE")
);
CREATE TABLE computer_programmer (
	"AREA" int,
	"AREA_TITLE" varchar(80),
	--"AREA_TYPE" int,
	--"PRIM_STATE" varchar(3),
	--"NAICS" int,
	--"NAICS_TITLE" varchar(80),
	--"I_GROUP" varchar(80),
	--"OWN_CODE" int,
	"OCC_TITLE" varchar(80),
	"OCC_CODE" varchar,
	--"O_GROUP" varchar(30),
	"TOT_EMP" varchar,
	--"EMP_PRSE" varchar,
	"JOBS_1000" varchar,
	"LOC_QUOTIENT" varchar,
--	"PCT_TOTAL" varchar,
	--"MEAN_PRSE" varchar,
	"H_PCT10" varchar,
	"H_PCT25" varchar,
	"H_MEDIAN" varchar,
	"H_MEAN" varchar,
	"H_PCT75" varchar,
	"H_PCT90" varchar,
	"A_PCT10" varchar,
	"A_PCT25" varchar,
	"A_MEDIAN" varchar,
	"A_MEAN" varchar,
	"A_PCT75" varchar,
	"A_PCT90" varchar,
	--"ANNUAL" int,
	--"HOURLY" int,
	PRIMARY KEY ("AREA_TITLE")
);
CREATE TABLE web_developer (
	"AREA" int,
	"AREA_TITLE" varchar(80),
	--"AREA_TYPE" int,
	--"PRIM_STATE" varchar(3),
	--"NAICS" int,
	--"NAICS_TITLE" varchar(80),
	--"I_GROUP" varchar(80),
	--"OWN_CODE" int,
	"OCC_TITLE" varchar(80),
	"OCC_CODE" varchar,
	--"O_GROUP" varchar(30),
	"TOT_EMP" varchar,
	--"EMP_PRSE" varchar,
	"JOBS_1000" varchar,
	"LOC_QUOTIENT" varchar,
--	"PCT_TOTAL" varchar,
	--"MEAN_PRSE" varchar,
	"H_PCT10" varchar,
	"H_PCT25" varchar,
	"H_MEDIAN" varchar,
	"H_MEAN" varchar,
	"H_PCT75" varchar,
	"H_PCT90" varchar,
	"A_PCT10" varchar,
	"A_PCT25" varchar,
	"A_MEDIAN" varchar,
	"A_MEAN" varchar,
	"A_PCT75" varchar,
	"A_PCT90" varchar,
	--"ANNUAL" int,
	--"HOURLY" int,
	PRIMARY KEY ("AREA_TITLE")
);

CREATE TABLE data_scientist (
	"AREA" int,
	"AREA_TITLE" varchar(80),
	--"AREA_TYPE" int,
	--"PRIM_STATE" varchar(3),
	--"NAICS" int,
	--"NAICS_TITLE" varchar(80),
	--"I_GROUP" varchar(80),
	--"OWN_CODE" int,
	"OCC_TITLE" varchar(80),
	"OCC_CODE" varchar,
	--"O_GROUP" varchar(30),
	"TOT_EMP" varchar,
	--"EMP_PRSE" varchar,
	"JOBS_1000" varchar,
	"LOC_QUOTIENT" varchar,
--	"PCT_TOTAL" varchar,
	--"MEAN_PRSE" varchar,
	"H_PCT10" varchar,
	"H_PCT25" varchar,
	"H_MEDIAN" varchar,
	"H_MEAN" varchar,
	"H_PCT75" varchar,
	"H_PCT90" varchar,
	"A_PCT10" varchar,
	"A_PCT25" varchar,
	"A_MEDIAN" varchar,
	"A_MEAN" varchar,
	"A_PCT75" varchar,
	"A_PCT90" varchar,
	--"ANNUAL" int,
	--"HOURLY" int,
	PRIMARY KEY ("AREA_TITLE")
);